### ISSUE TITLE
Failed to find glide.yaml file

### ISSUE THREAD

**Issue by waliguder** [chappjc/dcrvanity#3]
glide install
[ERROR] Failed to find glide.yaml file in directory tree: Cannot resolve parent of C:\

**Comment by waliguder** [comment]
This problem has been solved, although the error is reported, but it is actually successful, glide -version returns version information

**Comment by waliguder** [comment]
Use dcrlabs/dcrvanity!!!
But when I executed go build, I still got a mistake, as follows：
`# github.com/dcrlabs/dcrvanity/wif
..\..\github.com\dcrlabs\dcrvanity\wif\wif.go:95:42: too many arguments in call to secp256k1.PrivKeyFromBytes
        have (*secp256k1.KoblitzCurve, []byte)
        want ([]byte)`
Is it wrong with me? By the way, I am manually executing 
git clone https://github.com/btcsuite/golangcrypto $GOPATH/src/github.com/btcsuite/golangcrypto

**Comment by waliguder** [comment]
@chappjc @g0blinResearch Can you help me out of the woods? My operating environment is:
win10/amd64
go:1.9.2
glide:0.13.2-dev

**Comment by chappjc** [comment]
dcrvanity is now maintained in https://github.com/dcrlabs/dcrvanity
It is necessary to use go 1.10 with vgo, or go 1.10 (module-enabled).
